/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import klinik.Database;
import klinik.Bookingpasien;
import klinik.Dokter;

/**
 *
 * @author EXPERT-BOOK-USER
 */
public class CekBooking extends javax.swing.JFrame {

    /**
     * Creates new form CekBooking
     */
    public CekBooking() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tampilkan();
    }

    private void tampilkan() {
        Database konek = new Database();
        
        konek.openConnection();
        
        ArrayList<ArrayList> user = konek.all("SELECT * FROM booking");
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Tanggal");
        model.addColumn("Nama Pasien"); 
        model.addColumn("ID Dokter");
        model.addColumn("Layanan");
        model.addColumn("Status");
        
        
        for (ArrayList<String> rowData : user) {
            model.addRow(rowData.toArray());
        }
        
        konek.closeConnection();
        tabel_booking.setModel(model);                                     
    }    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_booking = new javax.swing.JTable();
        Edit = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtNamapasien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIDDokter = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLayanan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Delete1 = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("BOOKING");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabel_booking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_bookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_booking);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 500, 390));

        Edit.setBackground(new java.awt.Color(102, 51, 0));
        Edit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 140, 50));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 280, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        txtTanggal.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggal.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 280, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        txtNamapasien.setBackground(new java.awt.Color(255, 255, 255));
        txtNamapasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNamapasien.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(txtNamapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 280, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pasien");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        txtIDDokter.setBackground(new java.awt.Color(255, 255, 255));
        txtIDDokter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIDDokter.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(txtIDDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 280, 40));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        txtLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtLayanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLayanan.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(txtLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 280, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Layanan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dokter");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        Delete1.setBackground(new java.awt.Color(102, 51, 0));
        Delete1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete1.setText("Delete");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });
        getContentPane().add(Delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 140, 50));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(102, 51, 0));
        back.setText("KEMBALI");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Status");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        txtstatus.setBackground(new java.awt.Color(255, 255, 255));
        txtstatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtstatus.setForeground(new java.awt.Color(102, 51, 0));
        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "confirmed", "pending", "canceled" }));
        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rgistras (3) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here
        java.sql.Date df = new java.sql.Date(txtTanggal.getDate(). getTime());
        String ID = this.txtID.getText().trim();
        String Namapasien = this.txtNamapasien.getText().trim();
        String IDDokter = this.txtIDDokter.getText().trim();
        String Layanan = this.txtLayanan.getText().trim();
        String Status = (String) this.txtstatus.getSelectedItem();


        if (ID.isEmpty() || Namapasien.isEmpty() || IDDokter.isEmpty() || Layanan.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong");
        } else { 
            Bookingpasien booking = new Bookingpasien();
            booking.ID = ID ;
            booking.tanggal = df;
            booking.namapasien = Namapasien;
            booking.IDdokter = IDDokter;
            booking.layanan = Layanan;
            booking.status = Status;
;
            if (booking.update()) {
                JOptionPane.showMessageDialog(this, "Data berhasil diedit");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan");
            }    
          }
    }//GEN-LAST:event_EditActionPerformed

    private void tabel_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_bookingMouseClicked
        // TODO add your handling code here:
        int row = tabel_booking.rowAtPoint(evt.getPoint());
        String ID = tabel_booking.getValueAt(row, 0).toString();
        txtID.setText(ID);

        String dateStr = tabel_booking.getValueAt(row, 1).toString();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); //
        Date date = null;
        try {
            date = df.parse(dateStr);
        } catch (ParseException ex) {
            Logger.getLogger(Dokter.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTanggal.setDate(date);
        
        String namapasien = tabel_booking.getValueAt(row, 2).toString();
        txtNamapasien.setText(namapasien);
        
        String IDDokter = tabel_booking.getValueAt(row,3).toString();
        txtIDDokter.setText(IDDokter);
        
        String Layanan = tabel_booking.getValueAt(row,4).toString();
        txtLayanan.setText(Layanan);
        
        String Status = tabel_booking.getValueAt(row,4).toString();
        txtstatus.setSelectedItem(Status);
    }//GEN-LAST:event_tabel_bookingMouseClicked

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1ActionPerformed
        // TODO add your handling code here:
        String ID = txtID.getText();
        Bookingpasien booking = new Bookingpasien();
        booking.ID = ID;
        if (booking.delete()){
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            System.out.println("Data berhasil dihapus");
            tampilkan();
        }
    }//GEN-LAST:event_Delete1ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new Home_Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete1;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_booking;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDDokter;
    private javax.swing.JTextField txtLayanan;
    private javax.swing.JTextField txtNamapasien;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JComboBox<String> txtstatus;
    // End of variables declaration//GEN-END:variables
}
