/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import javax.swing.JOptionPane;

/**
 *
 * @author EXPERT-BOOK-USER
 */
public class Home_Pasien extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Pasien
     */
    public Home_Pasien() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booking = new javax.swing.JButton();
        Layanan = new javax.swing.JButton();
        kwmbali = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dokter1 = new javax.swing.JButton();
        kembali = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booking.setBackground(new java.awt.Color(102, 51, 0));
        booking.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        booking.setText("Booking");
        booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingActionPerformed(evt);
            }
        });
        getContentPane().add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 140, 80));

        Layanan.setBackground(new java.awt.Color(247, 215, 148));
        Layanan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Layanan.setForeground(new java.awt.Color(102, 51, 0));
        Layanan.setText("Layanan");
        Layanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LayananActionPerformed(evt);
            }
        });
        getContentPane().add(Layanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 140, 80));

        kwmbali.setBackground(new java.awt.Color(102, 51, 0));
        kwmbali.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kwmbali.setForeground(new java.awt.Color(255, 255, 255));
        kwmbali.setText("KEMBALI");
        kwmbali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwmbaliActionPerformed(evt);
            }
        });
        getContentPane().add(kwmbali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        keluar.setBackground(new java.awt.Color(102, 51, 0));
        keluar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LuxeSkin (1) (3).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, 150));

        dokter1.setBackground(new java.awt.Color(102, 51, 0));
        dokter1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dokter1.setText("Dokter");
        dokter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokter1ActionPerformed(evt);
            }
        });
        getContentPane().add(dokter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 140, 80));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4.png"))); // NOI18N
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void kwmbaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kwmbaliActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kwmbaliActionPerformed

    private void bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingActionPerformed
        // TODO add your handling code here:
        new Menu_Dokter().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookingActionPerformed

    private void LayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LayananActionPerformed
        // TODO add your handling code here:
        new Menu_Pelayanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LayananActionPerformed

    private void dokter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dokter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Layanan;
    private javax.swing.JButton booking;
    private javax.swing.JButton dokter1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel kembali;
    private javax.swing.JButton kwmbali;
    // End of variables declaration//GEN-END:variables
}
