/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import klinik.Database;
import klinik.Layanan;

/**
 *
 * @author EXPERT-BOOK-USER
 */
public class Menu_Pelayanan extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Pelayanan
     */
    public Menu_Pelayanan() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        rdit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_layanan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtdurasi = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtkategori = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(102, 51, 0));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 210, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        txtHarga.setBackground(new java.awt.Color(255, 255, 255));
        txtHarga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(102, 51, 0));
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 210, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("LAYANAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        save.setBackground(new java.awt.Color(102, 51, 0));
        save.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 120, 40));

        rdit.setBackground(new java.awt.Color(102, 51, 0));
        rdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdit.setText("Edit");
        rdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rditActionPerformed(evt);
            }
        });
        getContentPane().add(rdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 120, 40));

        delete.setBackground(new java.awt.Color(102, 51, 0));
        delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 120, 40));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(102, 51, 0));
        back.setText("KEMBALI");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabel_layanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabel_layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_layananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_layanan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 620, 220));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        txtdurasi.setBackground(new java.awt.Color(255, 255, 255));
        txtdurasi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdurasi.setForeground(new java.awt.Color(102, 51, 0));
        txtdurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurasiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 210, 40));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(102, 51, 0));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 210, 40));

        txtkategori.setBackground(new java.awt.Color(255, 255, 255));
        txtkategori.setForeground(new java.awt.Color(102, 51, 0));
        txtkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hair", "face", "body" }));
        getContentPane().add(txtkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 210, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Durasi");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kategori");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        txtstatus.setBackground(new java.awt.Color(255, 255, 255));
        txtstatus.setForeground(new java.awt.Color(102, 51, 0));
        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aktif", "tidak aktif" }));
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/7_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Durasi");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new Home_Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String id = this.txtID.getText().trim();
        String Nama = this.txtNama.getText().trim();
        String Harga = this.txtHarga.getText().trim();String 
        Status = (String) this.txtstatus.getSelectedItem();
        String Durasi = this.txtdurasi.getText().trim();
        String Kategori = (String) this.txtkategori.getSelectedItem();
        

        if (id.isEmpty() || Nama.isEmpty() || Harga.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong");
        } else { 
            Layanan layanan = new Layanan();
            layanan.ID = id;
            layanan.nama = Nama;
            layanan.harga = Harga;
            layanan.status = Status;
            layanan.durasi = Durasi;
            layanan.kategori = Kategori;

            if (layanan.create()) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan");
            }
        }
    }           
    
    private void tampilkan() {
        Database konek = new Database();
        
        konek.openConnection();
        
        ArrayList<ArrayList> user = konek.all("SELECT * FROM layanan");
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Harga");
        model.addColumn("Status");
        model.addColumn("Durasi");
        model.addColumn("Kategori");
        
        for (ArrayList<String> rowData : user) {
            model.addRow(rowData.toArray());
        }
        
        konek.closeConnection();
        tabel_layanan.setModel(model);     
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String id = this.txtID.getText();
        Layanan layanan = new Layanan();
        layanan.ID = id;
        if (layanan.delete()){
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            System.out.println("Data berhasil dihapus");
            tampilkan();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void rditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rditActionPerformed
        String id = this.txtID.getText().trim();
        String Nama = this.txtNama.getText().trim();
        String Harga = this.txtHarga.getText().trim();
        String Status = (String) this.txtstatus.getSelectedItem();
        String Durasi = this.txtdurasi.getText().trim();
        String Kategori = (String) this.txtkategori.getSelectedItem();

        if (id.isEmpty() || Nama.isEmpty() || Harga.isEmpty() || Status.isEmpty() || Durasi.isEmpty() || Kategori.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong");
        } else { 
            Layanan layanan = new Layanan();
            layanan.ID = id ;
            layanan.nama = Nama;
            layanan.harga = Harga;
            layanan.status = Status;
            layanan.durasi = Durasi;
            layanan.kategori = Kategori;
            

            if (layanan.update()) {
                JOptionPane.showMessageDialog(this, "Data berhasil diedit");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan");
            }    
          }

    }//GEN-LAST:event_rditActionPerformed

    private void txtdurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurasiActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void tabel_layananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_layananMouseClicked
        // TODO add your handling code here:
        int row = tabel_layanan.rowAtPoint(evt.getPoint());
        String id = tabel_layanan.getValueAt(row, 0).toString();
        this.txtID.setText(id);

        String nama = tabel_layanan.getValueAt(row, 1).toString();
        txtNama.setText(nama);

        String Harga = tabel_layanan.getValueAt(row,2).toString();
        txtHarga.setText(Harga);
        
        String Status = tabel_layanan.getValueAt(row,3).toString();
        txtstatus.setSelectedItem(Status);
        
        String Durasi = tabel_layanan.getValueAt(row,4).toString();
        txtdurasi.setText(Durasi);
        
        String Kategori = tabel_layanan.getValueAt(row,5).toString();
        txtkategori.setSelectedItem(Kategori);
    }//GEN-LAST:event_tabel_layananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pelayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Pelayanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rdit;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel_layanan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtdurasi;
    private javax.swing.JComboBox<String> txtkategori;
    private javax.swing.JComboBox<String> txtstatus;
    // End of variables declaration//GEN-END:variables
}
