/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import klinik.Database;
import klinik.Dokter;
import klinik.Pasien;
import klinik.Transaksi;

/**
 *
 * @author EXPERT-BOOK-USER
 */
public class Menu_Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Transaksi
     */
    public Menu_Transaksi() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIDtrans = new javax.swing.JTextField();
        txtNamapasien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        txtIDdokter = new javax.swing.JTextField();
        txtLayanan = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("TRANSAKSI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        txtIDtrans.setBackground(new java.awt.Color(255, 255, 255));
        txtIDtrans.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIDtrans.setForeground(new java.awt.Color(102, 51, 0));
        txtIDtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDtransActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDtrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 220, 40));

        txtNamapasien.setBackground(new java.awt.Color(255, 255, 255));
        txtNamapasien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNamapasien.setForeground(new java.awt.Color(102, 51, 0));
        txtNamapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamapasienActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 220, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(102, 51, 0));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 220, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dokter");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pasien");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, 40));

        txtTanggal.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 220, 40));

        txtIDdokter.setBackground(new java.awt.Color(255, 255, 255));
        txtIDdokter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIDdokter.setForeground(new java.awt.Color(102, 51, 0));
        txtIDdokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDdokterActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDdokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 220, 40));

        txtLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtLayanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLayanan.setForeground(new java.awt.Color(102, 51, 0));
        txtLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLayananActionPerformed(evt);
            }
        });
        getContentPane().add(txtLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 220, 40));

        ID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Layanan");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, 40));

        Save.setBackground(new java.awt.Color(102, 51, 0));
        Save.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 120, 40));

        Delete.setBackground(new java.awt.Color(102, 51, 0));
        Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 120, 40));

        Edit.setBackground(new java.awt.Color(102, 51, 0));
        Edit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 120, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_transaksi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 540, 320));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(102, 51, 0));
        back.setText("KEMBALI");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/8_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDtransActionPerformed

    private void txtNamapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamapasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamapasienActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtIDdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDdokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDdokterActionPerformed

    private void txtLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLayananActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new Home_Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        java.sql.Date df = new java.sql.Date(txtTanggal.getDate(). getTime());
        String ID = this.txtIDtrans.getText().trim();
        String NamaPasien = this.txtNamapasien.getText().trim();
        String IDDokter = this.txtIDdokter.getText().trim();
        String Layanan = this.txtLayanan.getText().trim();
        String Total = this.txtTotal.getText().trim();


        if (ID.isEmpty() || NamaPasien.isEmpty() || IDDokter.isEmpty() || Layanan.isEmpty() || Total.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong");
        } else { 
            Transaksi transaksi = new Transaksi();
            transaksi.ID = ID;
            transaksi.namapasien = NamaPasien;
            transaksi.tanggal = df;
            transaksi.IDdokter = IDDokter;
            transaksi.layanan = Layanan;
            transaksi.total = Total;

            if (transaksi.create()) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan");
            }
        }
    }           
    
    private void tampilkan() {
        Database konek = new Database();
        
        konek.openConnection();
        
        ArrayList<ArrayList> user = konek.all("SELECT * FROM transaksi");
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Pasien"); 
        model.addColumn("Tanggal");
        model.addColumn("ID Dokter");
        model.addColumn("Layanan");
        model.addColumn("Total");
        
        
        for (ArrayList<String> rowData : user) {
            model.addRow(rowData.toArray());
        }
        
        konek.closeConnection();
        tabel_transaksi.setModel(model);                                     
    }//GEN-LAST:event_SaveActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        java.sql.Date df = new java.sql.Date(txtTanggal.getDate(). getTime());
        String ID = this.txtIDtrans.getText().trim();
        String Namapasien = this.txtNamapasien.getText().trim();
        String IDDokter = this.txtIDdokter.getText().trim();
        String Layanan = this.txtLayanan.getText().trim();
        String Total = this.txtTotal.getText().trim();


        if (ID.isEmpty() || Namapasien.isEmpty() || IDDokter.isEmpty() || Layanan.isEmpty() || Total.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong");
        } else { 
            Transaksi transaksi = new Transaksi();
            transaksi.ID = ID ;
            transaksi.namapasien = Namapasien;
            transaksi.tanggal = df;
            transaksi.IDdokter = IDDokter;
            transaksi.layanan = Layanan;
            transaksi.total = Total;

            if (transaksi.update()) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan");
            }    
          }
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String ID = txtIDtrans.getText();
        Transaksi transaksi = new Transaksi();
        transaksi.ID = ID;
        if (transaksi.delete()){
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            System.out.println("Data berhasil dihapus");
            tampilkan();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
        // TODO add your handling code here:
        int row = tabel_transaksi.rowAtPoint(evt.getPoint());
        String ID = tabel_transaksi.getValueAt(row, 0).toString();
        txtIDtrans.setText(ID);

        String namapasien = tabel_transaksi.getValueAt(row, 1).toString();
        txtNamapasien.setText(namapasien);

        String dateStr = tabel_transaksi.getValueAt(row, 2).toString();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); //
        Date date = null;
        try {
            date = df.parse(dateStr);
        } catch (ParseException ex) {
            Logger.getLogger(Dokter.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTanggal.setDate(date);
        
        
        String IDDokter = tabel_transaksi.getValueAt(row,3).toString();
        txtIDdokter.setText(IDDokter);
        
        String Layanan = tabel_transaksi.getValueAt(row,4).toString();
        txtLayanan.setText(Layanan);

        String Total = tabel_transaksi.getValueAt(row, 5).toString();
        txtTotal.setText(Total);
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel ID;
    private javax.swing.JButton Save;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_transaksi;
    private javax.swing.JTextField txtIDdokter;
    private javax.swing.JTextField txtIDtrans;
    private javax.swing.JTextField txtLayanan;
    private javax.swing.JTextField txtNamapasien;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
