/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import klinik.Database;
import klinik.Dokter;
import klinik.Pasien;

/**
 *
 * @author EXPERT-BOOK-USER
 */
public class Menu_Pasien extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Pasien
     */
    public Menu_Pasien() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pasien = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        txtKeluhan = new javax.swing.JTextField();
        txtAalamat = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(102, 51, 0));
        back.setText("KEMBALI");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabel_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabel_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pasien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 520, 270));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(102, 51, 0));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 220, 40));

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(102, 51, 0));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 220, 40));

        txtTanggal.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 220, 40));

        txtKeluhan.setBackground(new java.awt.Color(255, 255, 255));
        txtKeluhan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtKeluhan.setForeground(new java.awt.Color(102, 51, 0));
        txtKeluhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeluhanActionPerformed(evt);
            }
        });
        getContentPane().add(txtKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 220, 40));

        txtAalamat.setBackground(new java.awt.Color(255, 255, 255));
        txtAalamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAalamat.setForeground(new java.awt.Color(102, 51, 0));
        txtAalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 220, 40));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 51, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 220, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lahir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Keluhan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("Alamat");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        txtNoHp.setBackground(new java.awt.Color(255, 255, 255));
        txtNoHp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNoHp.setForeground(new java.awt.Color(102, 51, 0));
        txtNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHpActionPerformed(evt);
            }
        });
        getContentPane().add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 220, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("No HP");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, 40));

        Save.setBackground(new java.awt.Color(102, 51, 0));
        Save.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 120, 40));

        Edit.setBackground(new java.awt.Color(102, 51, 0));
        Edit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 120, 40));

        Delete.setBackground(new java.awt.Color(102, 51, 0));
        Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 120, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("PASIEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/9.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new Home_Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtKeluhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeluhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeluhanActionPerformed

    private void txtAalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAalamatActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHpActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        java.sql.Date df = new java.sql.Date(txtTanggal.getDate(). getTime());
        String ID = this.txtID.getText().trim();
        String Nama = this.txtNama.getText().trim();
        String Keluhan = this.txtKeluhan.getText().trim();
        String Alamat = this.txtAalamat.getText().trim();
        String noHP = this.txtNoHp.getText().trim();
        String email = this.txtEmail.getText().trim();


        if (ID.isEmpty() || Nama.isEmpty() || Keluhan.isEmpty() || Alamat.isEmpty() || noHP.isEmpty() || email.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong");
        } else { 
            Pasien pasien = new Pasien();
            pasien.ID = ID;
            pasien.nama = Nama;
            pasien.tanggallahir = df;
            pasien.keluhan = Keluhan;
            pasien.alamat = Alamat;
            pasien.nohp = noHP;
            pasien.email = email;

            if (pasien.create()) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan");
            }
        }
    }           
    
    private void tampilkan() {
        Database konek = new Database();
        
        konek.openConnection();
        
        ArrayList<ArrayList> user = konek.all("SELECT * FROM pasien");
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama"); 
        model.addColumn("Tanggal Lahir");
        model.addColumn("Keluhan");
        model.addColumn("Alamat");
        model.addColumn("No HP");
        model.addColumn("Email");
        
        
        for (ArrayList<String> rowData : user) {
            model.addRow(rowData.toArray());
        }
        
        konek.closeConnection();
        tabel_pasien.setModel(model); 
    }//GEN-LAST:event_SaveActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        java.sql.Date df = new java.sql.Date(txtTanggal.getDate(). getTime());
        String ID = this.txtID.getText().trim();
        String Nama = this.txtNama.getText().trim();
        String Keluhan = this.txtKeluhan.getText().trim();
        String Alamat = this.txtAalamat.getText().trim();
        String noHP = this.txtNoHp.getText().trim();
        String email = this.txtEmail.getText().trim();


        if (ID.isEmpty() || Nama.isEmpty() || Keluhan.isEmpty() || Alamat.isEmpty() || noHP.isEmpty() || email.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong");
        } else { 
            Pasien pasien = new Pasien();
            pasien.ID = ID ;
            pasien.nama = Nama;
            pasien.tanggallahir = df;
            pasien.keluhan = Keluhan;
            pasien.alamat = Alamat;
            pasien.nohp = noHP;
            pasien.email = email;

            if (pasien.update()) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan");
            }    
          }
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String ID = txtID.getText();
        Pasien pasien = new Pasien();
        pasien.ID = ID;
        if (pasien.delete()){
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            System.out.println("Data berhasil dihapus");
            tampilkan();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void tabel_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pasienMouseClicked
        // TODO add your handling code here:
        int row = tabel_pasien.rowAtPoint(evt.getPoint());
        String ID = tabel_pasien.getValueAt(row, 0).toString();
        txtID.setText(ID);

        String nama = tabel_pasien.getValueAt(row, 1).toString();
        txtNama.setText(nama);

        String dateStr = tabel_pasien.getValueAt(row, 2).toString();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); //
        Date date = null;
        try {
            date = df.parse(dateStr);
        } catch (ParseException ex) {
            Logger.getLogger(Dokter.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTanggal.setDate(date);
        
        
        String Keluhan = tabel_pasien.getValueAt(row,3).toString();
        txtKeluhan.setText(Keluhan);
        
        String Alamat = tabel_pasien.getValueAt(row,4).toString();
        txtAalamat.setText(Alamat);

        String nohp = tabel_pasien.getValueAt(row, 5).toString();
        txtNoHp.setText(nohp);
        
        String email = tabel_pasien.getValueAt(row, 6).toString();
        txtEmail.setText(email);
    }//GEN-LAST:event_tabel_pasienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Save;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_pasien;
    private javax.swing.JTextField txtAalamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKeluhan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    private com.toedter.calendar.JDateChooser txtTanggal;
    // End of variables declaration//GEN-END:variables
}
