/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import klinik.Database;

import klinik.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class Registrasi extends javax.swing.JFrame {
    Database db = new Database();
    public static String Username;
    public static String password;
    public static String txtperan;
    
    public Registrasi() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Registrasi = new javax.swing.JButton();
        verifypass = new javax.swing.JPasswordField();
        txtpass = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        perann = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Peran");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Verify Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("REGISTASI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Username ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        Registrasi.setBackground(new java.awt.Color(102, 51, 0));
        Registrasi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Registrasi.setText("Registrasi");
        Registrasi.setToolTipText("");
        Registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrasiActionPerformed(evt);
            }
        });
        getContentPane().add(Registrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 120, 60));

        verifypass.setBackground(new java.awt.Color(247, 215, 148));
        verifypass.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(verifypass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 300, 40));

        txtpass.setBackground(new java.awt.Color(247, 215, 148));
        txtpass.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 300, 40));

        txtuser.setBackground(new java.awt.Color(247, 215, 148));
        txtuser.setForeground(new java.awt.Color(102, 51, 0));
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 300, 40));

        perann.setBackground(new java.awt.Color(247, 215, 148));
        perann.setForeground(new java.awt.Color(102, 51, 0));
        perann.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pasien", " " }));
        getContentPane().add(perann, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 300, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rgistras (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrasiActionPerformed
        // TODO add your handling code here:
        String username = txtuser.getText();
        String peran = (String) this.perann.getSelectedItem();
        String password =  String.copyValueOf(txtpass.getPassword());
        String conPassword =  String.copyValueOf(verifypass.getPassword());
        
        if (username.equals("") || peran.equals("") || password.equals("") || conPassword.equals("")){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
        } else if (password.equals(conPassword)) {
            try{
                String query = String.format("INSERT INTO login VALUES ('%s','%s','%s')",username,peran,password);
                db.execute(query);
                JOptionPane.showMessageDialog(null, "Pembuatan Akun Berhasil, Silahkan Login Kembali");
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(this,"This Account is Already exist / Duplicate Account ", "Pesan",JOptionPane.WARNING_MESSAGE);
                System.out.println("Error");
            } finally{
                this.dispose();
                Login login = new Login();
                login.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password tidak sama");
        }   
    }//GEN-LAST:event_RegistrasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> perann;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    private javax.swing.JPasswordField verifypass;
    // End of variables declaration//GEN-END:variables
}
